[[entries]]
title = "Valentine's Day NPCs are Becoming Smart Vinyl"
img = "valentines-album-cover.png"
width = "600px"
tracks = [
       "Ending Theme (Valentine's Day Edition)",
       "Outside Theme (Valentine's Day Edition)",
       "Reversed (Valentine's Day Edition)",
]
