[[entries]]
title = "Sunny's Arcade"
img = "sunny-arcade.png"

[[entries]]
title = "Sunny's Arcade (Nintendo Edition)"
img = "sunny-nintendo.png"

[[entries]]
title = "What happens if you dig straight down"
img = "what_happens_if_you_dig_straight_down.gif"