[[entries]]
title = "Breaking the Bank Again (Like, Literally)"
type = "book"

[[entries.pages]]
img = "book/00.jpg"
text = ""

[[entries.pages]]
img = "book/01.jpg"
text = '''

Henry got the diamond tooken away because of stealing it. And he knew that they
took it to the bank. 

'''

[[entries.pages]]
img = "book/02.jpg"
text = '''

Henry has to make some choices and use two things to smash down the wall of the
bank.

'''

[[entries.pages]]
img = "book/03.jpg"
text = '''

Henry chose the pickaxe

'''

[[entries.pages]]
img = "book/04.jpg"
text = '''

He mines...

'''

[[entries.pages]]
img = "book/05.jpg"
text = '''

And he mi...
<br />
<i>Hssssss</i>
<br />
BOOM!
<br />
A creeper exploded!

'''

[[entries.pages]]
img = "book/06.jpg"
text = "But that wasn't bad because the creeper didn't take much damage. <br /> And he landed right on the diamond case and the diamond case cracked!"

[[entries.pages]]
img = "book/07.jpg"
text = "And he got the diamond"

[[entries.pages]]
img = "book/08.jpg"
text = "But then the police ran after him"

[[entries.pages]]
img = "book/09.jpg"
text = "But then he ran into a cliff and fell off!"

[[entries.pages]]
img = "book/10.jpg"
text = "But that wasn't bad because the diamond wasn't broken!"

[[entries.pages]]
img = "book/11.jpg"
text = "And he got it back"

[[entries.pages]]
img = "book/12.jpg"
text = "The End"

[[entries.pages]]
img = "book/13.jpg"