[gpb]

[[gpb.entries]]
  type = "created_site"
  date = 2025-02-16
  comment = '''
    Ghostlypumpkinboy expressed a desire to create a website, and I said "I know
    how to do that!"

    And so here we are!
    '''
[gpb.entries.content]
domain = "ghostlypumpkinboy.me"
slug = "gpb"

[[gpb.entries]]
  type = "created_page"
  date = 2025-02-16
  comment = '''
    Of course, it all starts with the first page. We decided to go with a gallery
    on the index page for all of GPB's drawings. People love the "Sorry, more
    later" link at the bottom
    '''
[gpb.entries.content]
page = "index"
title = "Gallery"

[[gpb.index.entries]]
  type = "created_slug"
  date = 2025-02-16
  comment = '''
    The image was described as being his wildest minecraft inventions, but which
    inventions it actually depicts is as-of-yet undisclosed.

    On a personal note, I had to get these art pieces off of his iPad, and I had a
    devil of a time getting Ubuntu Noble Server to have a writeable Samba share,
    but maybe I was misreading the iPad's interface.
    '''
[gpb.index.entries.content]
slug = "minecraft_inventions"
img = "minecraft-inventions.png"
width = "600px"

[[gpb.index.entries]]
  type = "created_slug"
  date = 2025-02-17

  comment = '''
    Initially he asked me to help him spell "Escape Prison" he's been doing this
    thing where when the layout of words doesn't go as he expected, he writes the
    stuff doesn't fit on the line _above_ the line instead.

    So this one says "Prison Escape". He says that's what he meant to do anyway
    '''
[gpb.index.entries.content]
slug = "prison_escape"
img = "prison_escape.png"
width = "600px"

[[gpb.entries]]
  type = "created_page"
  date = 2025-02-17
  comment = '''
    The idea for an update log came from GPB independently and very early on. I
    think he got the idea from video game updates?
    '''
[gpb.entries.content]
page = "update_log"
title = "Update Log"

[[gpb.entries]]
  type = "updated_site"
  date = 2025-02-19
  comment = '''
    The only idea of mine he took: adding a menu bar with links between pages
    '''
[gpb.entries.content]
text = "Added menu bar"

[[gpb.entries]]
  type = "updated_page"
  date = 2025-02-19
  comment = '''
    He wanted to point out that the original color scheme was meant to indicate
    a fire/ice summer/winter vibe
    '''
[gpb.entries.content]
page = "index"
title = ["It's Summer v", "s Winter" ]

[[gpb.index.entries]]
  type = "created_slug"
  date = 2025-02-19
  comment = '''
    Hand drawn, took a picture with my S24 Ultra and desaturated it to mimic scanning.
    '''
[gpb.index.entries.content]
slug = "sonic_running_downstairs"
img = "sonic-running-downstairs.jpg"
width = "600px"


[[gpb.entries]]
  type = "created_page"
  date = 2025-02-19
  comment = '''
    He had this idea that he would have a fan music page, but it would just have
    album art and track listings. We talked about adding soundcloud or something
    like that so he could make/post music, but he seems unsure about his ability to
    record the music he hears in his head still.

    I like it, it reminds of fan websites in the early 2000s before wikis absorbed
    everything.
    '''
[gpb.entries.content]
page = "fan_music_page"
title = "Fan Music Page"

[[gpb.fan_music_page.entries]]
  type = "created_slug"
  date = 2025-02-19
  comment = '''
    This is the first fan music album. It's based on music from the Roblox game
    "NPCs are Becoming Smart". The cover art depicts "Carl" (right), a
    robot-voiced NPC from the game, and "Narl" (left), Negative Carl from a
    surprise negative world in the game.

    I helped him write the text.
    '''
[gpb.fan_music_page.entries.content]
slug = "valentines_npc_vinyl"
title = "Valentine's Day NPCs are Becoming Smart Vinyl"
img = "valentines-album-cover.png"
width = "600px"
tracks = [
  "Ending Theme (Valentine's Day Edition)",
  "Outside Theme (Valentine's Day Edition)",
  "Reversed (Valentine's Day Edition)",
]


[[gpb.entries]]
  type = "created_page"
  date = 2025-02-19
  comment = '''
    Initially he just wanted these images in the gallery, but then he decided he
    wanted them to be part of a new "Game Page"
    '''
[gpb.entries.content]
page = "game_page"
title = "Game Page"

[[gpb.game_page.entries]]
  type = "created_slug"
  date = 2025-02-19
  comment = '''
    "Sunny's Arcade", made in a pixel art app
    '''
[gpb.game_page.entries.content]
slug = "sunnys_arcade"
title = "Sunny's Arcade"
img = "sunny-arcade.png"
width = "512px"

[[gpb.game_page.entries]]
  type = "created_slug"
  date = 2025-02-19
  comment = '''
    "Sunny's Arcade (Nintendo Edition)", I'm not sure what gives him the vibe that
    this is a "Nintendo Edition" but I've learned not to argue with classifications
    like this
    '''
[gpb.game_page.entries.content]
slug = "sunnys_arcade_nintendo_edition"
title = "Sunny's Arcade (Nintendo Edition)"
img = "sunny-nintendo.png"
width = "512px"

[[gpb.entries]]
type = "created_page"
date = 2025-02-27
comment = '''
  This is the first time I use my inflence to suggest something he didn't want
  at first. He made this book at school and he wanted to make it into an
  animation first before posting it. Keeping in mind the likelihood such an
  animation would ever be finished, I convinced him to the idea of having a
  "prototypes" page we post the book to first.
  '''
[gpb.entries.content]
page = "prototypes"
title = "Prototypes"

[[gpb.prototypes.entries]]
type = "created_slug"
date = 2025-02-27
comment = '''
  "Breaking the Bank Again (Like, Literally)" is based on a video game called
  "Henry Stickmin", where a stickman named Henry breaks into a heavily guarded
  area to steal a diamond. It is best classified as a "Clickamajig" crossed with
  a choose-your-own-adventure.
'''

[gpb.prototypes.entries.content]
slug = "btba"
title = "Breaking the Bank Again (Like, Literally)"
type = "book"

[[gpb.prototypes.btba.entries]]
type = "created_slug"
date = 2025-02-27

[gpb.prototypes.btba.entries.content]
slug = "btba-00"
type = "page"
img = "book/00.jpg"
text = ""

[[gpb.prototypes.btba.entries]]
type = "created_slug"
date = 2025-02-27

[gpb.prototypes.btba.entries.content]
slug = "btba-01"
type = "page"
img = "book/01.jpg"
text = '''
Henry got the diamond tooken away because of stealing it. And he knew that they
took it to the bank. 
'''

[[gpb.prototypes.btba.entries]]
type = "created_slug"
date = 2025-02-27

[gpb.prototypes.btba.entries.content]
slug = "btba-02"
type = "page"
img = "book/02.jpg"
text = '''

Henry has to make some choices and use two things to smash down the wall of the
bank.

'''

[[gpb.prototypes.btba.entries]]
type = "created_slug"
date = 2025-02-27

[gpb.prototypes.btba.entries.content]
slug = "btba-03"
type = "page"
img = "book/03.jpg"
text = '''

Henry chose the pickaxe

'''

[[gpb.prototypes.btba.entries]]
type = "created_slug"
date = 2025-02-27

[gpb.prototypes.btba.entries.content]
slug = "btba-04"
type = "page"
img = "book/04.jpg"
text = '''

He mines...

'''

[[gpb.prototypes.btba.entries]]
type = "created_slug"
date = 2025-02-27

[gpb.prototypes.btba.entries.content]
slug = "btba-05"
type = "page"
img = "book/05.jpg"
text = '''

And he mi...
<br />
<i>Hssssss</i>
<br />
BOOM!
<br />
A creeper exploded!

'''

[[gpb.prototypes.btba.entries]]
type = "created_slug"
date = 2025-02-27

[gpb.prototypes.btba.entries.content]
slug = "btba-06"
type = "page"
img = "book/06.jpg"
text = "But that wasn't bad because the creeper didn't take much damage. <br /> And he landed right on the diamond case and the diamond case cracked!"

[[gpb.prototypes.btba.entries]]
type = "created_slug"
date = 2025-02-27

[gpb.prototypes.btba.entries.content]
slug = "btba-07"
type = "page"
img = "book/07.jpg"
text = "And he got the diamond"

[[gpb.prototypes.btba.entries]]
type = "created_slug"
date = 2025-02-27

[gpb.prototypes.btba.entries.content]
slug = "btba-08"
type = "page"
img = "book/08.jpg"
text = "But then the police ran after him"

[[gpb.prototypes.btba.entries]]
type = "created_slug"
date = 2025-02-27

[gpb.prototypes.btba.entries.content]
slug = "btba-09"
type = "page"
img = "book/09.jpg"
text = "But then he ran into a cliff and fell off!"

[[gpb.prototypes.btba.entries]]
type = "created_slug"
date = 2025-02-27

[gpb.prototypes.btba.entries.content]
slug = "btba-10"
type = "page"
img = "book/10.jpg"
text = "But that wasn't bad because the diamond wasn't broken!"

[[gpb.prototypes.btba.entries]]
type = "created_slug"
date = 2025-02-27

[gpb.prototypes.btba.entries.content]
slug = "btba-11"
type = "page"
img = "book/11.jpg"
text = "And he got it back"

[[gpb.prototypes.btba.entries]]
type = "created_slug"
date = 2025-02-27

[gpb.prototypes.btba.entries.content]
slug = "btba-12"
type = "page"
img = "book/12.jpg"
text = "The End"

[[gpb.prototypes.btba.entries]]
type = "created_slug"
date = 2025-02-27

[gpb.prototypes.btba.entries.content]
slug = "btba-13"
type = "page"
img = "book/13.jpg"
text = ""
